In [ ]:
%pip install seaborn
import pandas as pd
import sqlite3
import seaborn as sns
import matplotlib.pyplot as plt
%inline 

path = '../portfolio.db'
conn = sqlite3.connect(path)

cur = conn.cursor()

ModuleNotFoundError: No module named 'seaborn'

In [3]:
%pip install seaborn

Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages (from seaborn) (2.4.1)
Requirement already satisfied: pandas>=1.2 in /Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages (from seaborn) (3.0.0)
Collecting matplotlib!=3.6.1,>=3.4 (from seaborn)
  Using cached matplotlib-3.10.8-cp311-cp311-macosx_11_0_arm64.whl.metadata (52 kB)
Collecting contourpy>=1.0.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached contourpy-1.3.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached fonttools-4.61.1-cp311-cp311-macosx_10_9_universal2.whl.metadata (114 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached kiwisolver-1.4.9-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.3 kB)
Requirement already satisfied: packaging>=20.0 in /Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Collecting pillow>=8 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached pillow-12.1.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (8.8 kB)
Collecting pyparsing>=3 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in /Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached matplotlib-3.10.8-cp311-cp311-macosx_11_0_arm64.whl (8.1 MB)
Using cached contourpy-1.3.3-cp311-cp311-macosx_11_0_arm64.whl (270 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.61.1-cp311-cp311-macosx_10_9_universal2.whl (2.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 233.8 kB/s  0:00:11 eta 0:00:02
Downloading kiwisolver-1.4.9-cp311-cp311-macosx_11_0_arm64.whl (65 kB)
Downloading pillow-12.1.0-cp311-cp311-macosx_11_0_arm64.whl (4.7 MB)
   ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 2.4/4.7 MB 48.9 kB/s eta 0:00:48

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^
  File "/Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 102, in read
    self.__buf.write(data)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tempfile.py", line 483, in func_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 107, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "/Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 98, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 85, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 415, in run
    preparer.prepare_linked_requirements_more(
  File "/Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 570, in prepare_linked_requirements_more
    self._complete_partial_requirements(
  File "/Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 479, in _complete_partial_requirements
    for link, (filepath, _) in batch_download:
  File "/Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages/pip/_internal/network/download.py", line 184, in batch
    filepath, content_type = self(link, location)
                             ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages/pip/_internal/network/download.py", line 195, in __call__
    self._process_response(download, resp)
  File "/Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages/pip/_internal/network/download.py", line 212, in _process_response
    for chunk in chunks:
  File "/Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages/pip/_internal/cli/progress_bars.py", line 67, in _rich_download_progress_bar
    for chunk in iterable:
  File "/Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages/pip/_internal/network/utils.py", line 65, in response_chunks
    for chunk in response.raw.stream(
  File "/Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 560, in read
    with self._error_catcher():
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: OSError(28, 'No space left on device')", OSError(28, 'No space left on device'))
Note: you may need to restart the kernel to use updated packages.

### Extract from the file database

In [ ]:
sales_df = pd.read_sql("select * from Superstore", conn)
sales_df.head(10)

,RowID,OrderID,OrderDate,ShipDate,ShipMode,CustomerID,CustomerName,Segment,Country,City,...,PostalCode,Region,ProductID,Category,SubCategory,ProductName,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,7,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
8,9,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825
9,10,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700

### Transform

In [ ]:
print(sales_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   RowID         9994 non-null   int64
 1   OrderID       9994 non-null   str
 2   OrderDate     9994 non-null   datetime64[us]
 3   ShipDate      9994 non-null   datetime64[us]
 4   ShipMode      9994 non-null   str
 5   CustomerID    9994 non-null   str
 6   CustomerName  9994 non-null   str
 7   Segment       9994 non-null   str
 8   Country       9994 non-null   str
 9   City          9994 non-null   str
 10  State         9994 non-null   str
 11  PostalCode    9994 non-null   int64
 12  Region        9994 non-null   str
 13  ProductID     9994 non-null   str
 14  Category      9994 non-null   str
 15  SubCategory   9994 non-null   str
 16  ProductName   9994 non-null   str
 17  Sales         9994 non-null   float64
 18  Quantity      9994 non-null   int64
 19  Discount      9994 non-null   float64
 20  Profit        9994 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(3), str(13)
memory usage: 1.6 MB
None

In [ ]:
sales_df['OrderDate'] = pd.to_datetime(sales_df['OrderDate'], format='%m/%d/%Y')
print(sales_df.head(10))

   RowID         OrderID  OrderDate   ShipDate        ShipMode CustomerID  \
0      1  CA-2016-152156 2016-11-08 2016-11-11    Second Class   CG-12520
1      2  CA-2016-152156 2016-11-08 2016-11-11    Second Class   CG-12520
2      3  CA-2016-138688 2016-06-12 2016-06-16    Second Class   DV-13045
3      4  US-2015-108966 2015-10-11 2015-10-18  Standard Class   SO-20335
4      5  US-2015-108966 2015-10-11 2015-10-18  Standard Class   SO-20335
5      6  CA-2014-115812 2014-06-09 2014-06-14  Standard Class   BH-11710
6      7  CA-2014-115812 2014-06-09 2014-06-14  Standard Class   BH-11710
7      8  CA-2014-115812 2014-06-09 2014-06-14  Standard Class   BH-11710
8      9  CA-2014-115812 2014-06-09 2014-06-14  Standard Class   BH-11710
9     10  CA-2014-115812 2014-06-09 2014-06-14  Standard Class   BH-11710

      CustomerName    Segment        Country             City  ... PostalCode  \
0      Claire Gute   Consumer  United States        Henderson  ...      42420
1      Claire Gute   Consumer  United States        Henderson  ...      42420
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...      90036
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...      33311
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...      33311
5  Brosina Hoffman   Consumer  United States      Los Angeles  ...      90032
6  Brosina Hoffman   Consumer  United States      Los Angeles  ...      90032
7  Brosina Hoffman   Consumer  United States      Los Angeles  ...      90032
8  Brosina Hoffman   Consumer  United States      Los Angeles  ...      90032
9  Brosina Hoffman   Consumer  United States      Los Angeles  ...      90032

   Region        ProductID         Category  SubCategory  \
0   South  FUR-BO-10001798        Furniture    Bookcases
1   South  FUR-CH-10000454        Furniture       Chairs
2    West  OFF-LA-10000240  Office Supplies       Labels
3   South  FUR-TA-10000577        Furniture       Tables
4   South  OFF-ST-10000760  Office Supplies      Storage
5    West  FUR-FU-10001487        Furniture  Furnishings
6    West  OFF-AR-10002833  Office Supplies          Art
7    West  TEC-PH-10002275       Technology       Phones
8    West  OFF-BI-10003910  Office Supplies      Binders
9    West  OFF-AP-10002892  Office Supplies   Appliances

                                         ProductName     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                     Eldon Fold 'N Roll Cart System   22.3680         2
5  Eldon Expressions Wood and Plastic Desk Access...   48.8600         7
6                                         Newell 322    7.2800         4
7                     Mitel 5320 IP Phone VoIP phone  907.1520         6
8  DXL Angle-View Binders with Locking Rings by S...   18.5040         3
9                   Belkin F5C206VTEL 6 Outlet Surge  114.9000         5

   Discount    Profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164
5      0.00   14.1694
6      0.00    1.9656
7      0.20   90.7152
8      0.20    5.7825
9      0.00   34.4700

[10 rows x 21 columns]

In [ ]:
sales_df['ShipDate'] = pd.to_datetime(sales_df['ShipDate'], format='%m/%d/%Y')
print(sales_df.head(10))

   RowID         OrderID  OrderDate   ShipDate        ShipMode CustomerID  \
0      1  CA-2016-152156 2016-11-08 2016-11-11    Second Class   CG-12520
1      2  CA-2016-152156 2016-11-08 2016-11-11    Second Class   CG-12520
2      3  CA-2016-138688 2016-06-12 2016-06-16    Second Class   DV-13045
3      4  US-2015-108966 2015-10-11 2015-10-18  Standard Class   SO-20335
4      5  US-2015-108966 2015-10-11 2015-10-18  Standard Class   SO-20335
5      6  CA-2014-115812 2014-06-09 2014-06-14  Standard Class   BH-11710
6      7  CA-2014-115812 2014-06-09 2014-06-14  Standard Class   BH-11710
7      8  CA-2014-115812 2014-06-09 2014-06-14  Standard Class   BH-11710
8      9  CA-2014-115812 2014-06-09 2014-06-14  Standard Class   BH-11710
9     10  CA-2014-115812 2014-06-09 2014-06-14  Standard Class   BH-11710

      CustomerName    Segment        Country             City  ... PostalCode  \
0      Claire Gute   Consumer  United States        Henderson  ...      42420
1      Claire Gute   Consumer  United States        Henderson  ...      42420
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...      90036
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...      33311
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...      33311
5  Brosina Hoffman   Consumer  United States      Los Angeles  ...      90032
6  Brosina Hoffman   Consumer  United States      Los Angeles  ...      90032
7  Brosina Hoffman   Consumer  United States      Los Angeles  ...      90032
8  Brosina Hoffman   Consumer  United States      Los Angeles  ...      90032
9  Brosina Hoffman   Consumer  United States      Los Angeles  ...      90032

   Region        ProductID         Category  SubCategory  \
0   South  FUR-BO-10001798        Furniture    Bookcases
1   South  FUR-CH-10000454        Furniture       Chairs
2    West  OFF-LA-10000240  Office Supplies       Labels
3   South  FUR-TA-10000577        Furniture       Tables
4   South  OFF-ST-10000760  Office Supplies      Storage
5    West  FUR-FU-10001487        Furniture  Furnishings
6    West  OFF-AR-10002833  Office Supplies          Art
7    West  TEC-PH-10002275       Technology       Phones
8    West  OFF-BI-10003910  Office Supplies      Binders
9    West  OFF-AP-10002892  Office Supplies   Appliances

                                         ProductName     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                     Eldon Fold 'N Roll Cart System   22.3680         2
5  Eldon Expressions Wood and Plastic Desk Access...   48.8600         7
6                                         Newell 322    7.2800         4
7                     Mitel 5320 IP Phone VoIP phone  907.1520         6
8  DXL Angle-View Binders with Locking Rings by S...   18.5040         3
9                   Belkin F5C206VTEL 6 Outlet Surge  114.9000         5

   Discount    Profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164
5      0.00   14.1694
6      0.00    1.9656
7      0.20   90.7152
8      0.20    5.7825
9      0.00   34.4700

[10 rows x 21 columns]

In [ ]:
sales_df.head()

,RowID,OrderID,OrderDate,ShipDate,ShipMode,CustomerID,CustomerName,Segment,Country,City,...,PostalCode,Region,ProductID,Category,SubCategory,ProductName,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
sales_df['Sales'] = sales_df['Sales'].round(2)
sales_df['Profit'] = sales_df['Profit'].round(2)
print(sales_df.head())

   RowID         OrderID  OrderDate   ShipDate        ShipMode CustomerID  \
0      1  CA-2016-152156 2016-11-08 2016-11-11    Second Class   CG-12520
1      2  CA-2016-152156 2016-11-08 2016-11-11    Second Class   CG-12520
2      3  CA-2016-138688 2016-06-12 2016-06-16    Second Class   DV-13045
3      4  US-2015-108966 2015-10-11 2015-10-18  Standard Class   SO-20335
4      5  US-2015-108966 2015-10-11 2015-10-18  Standard Class   SO-20335

      CustomerName    Segment        Country             City  ... PostalCode  \
0      Claire Gute   Consumer  United States        Henderson  ...      42420
1      Claire Gute   Consumer  United States        Henderson  ...      42420
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...      90036
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...      33311
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...      33311

   Region        ProductID         Category SubCategory  \
0   South  FUR-BO-10001798        Furniture   Bookcases
1   South  FUR-CH-10000454        Furniture      Chairs
2    West  OFF-LA-10000240  Office Supplies      Labels
3   South  FUR-TA-10000577        Furniture      Tables
4   South  OFF-ST-10000760  Office Supplies     Storage

                                         ProductName   Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.96         2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.94         3
2  Self-Adhesive Address Labels for Typewriters b...   14.62         2
3      Bretford CR4500 Series Slim Rectangular Table  957.58         5
4                     Eldon Fold 'N Roll Cart System   22.37         2

   Discount  Profit
0      0.00   41.91
1      0.00  219.58
2      0.00    6.87
3      0.45 -383.03
4      0.20    2.52

[5 rows x 21 columns]

In [ ]:
sales_df.describe(exclude=['str'])

,RowID,OrderDate,ShipDate,PostalCode,Sales,Quantity,Discount,Profit
count,9994.000000,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2016-04-30 00:07:12.259355,2016-05-03 23:06:58.571142,55190.379428,229.857980,3.789574,0.156203,28.656848
min,1.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,1040.000000,0.440000,1.000000,0.000000,-6599.980000
25%,2499.250000,2015-05-23 00:00:00,2015-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.730000
50%,4997.500000,2016-06-26 00:00:00,2016-06-29 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.665000
75%,7495.750000,2017-05-14 00:00:00,2017-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.360000
max,9994.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.980000
std,2885.163629,NaN,NaN,32063.693350,623.245104,2.225110,0.206452,234.260149

In [ ]:
# check for date inconsistency
print("checking for date inconsistencies...")
inconsistency = sales_df[sales_df['OrderDate']>sales_df['ShipDate']][['OrderID','OrderDate','ShipDate']]

if inconsistency.isnull:
    print("All order dates are consistent (OrderDate < ShipDate)")
else:
    print("Date consistency is detected:")
    print(inconsistency)

checking for date inconsistencies...
All order dates are consistent (OrderDate < ShipDate)

In [ ]:
sales_df['Sales'].plot()

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.