In [2]:
import pandas as pd
import sqlite3
import seaborn as sns
import matplotlib.pyplot as plt

path = '../portfolio.db'
conn = sqlite3.connect(path)

cur = conn.cursor()

### Extract from the file database

In [4]:
sales_df = pd.read_sql("select * from Superstore", conn)
sales_df.head(10)

,RowID,OrderID,OrderDate,ShipDate,ShipMode,CustomerID,CustomerName,Segment,Country,City,...,PostalCode,Region,ProductID,Category,SubCategory,ProductName,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,7,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
8,9,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825
9,10,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700

### Transform

In [5]:
print(sales_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   RowID         9994 non-null   int64
 1   OrderID       9994 non-null   str
 2   OrderDate     9994 non-null   str
 3   ShipDate      9994 non-null   str
 4   ShipMode      9994 non-null   str
 5   CustomerID    9994 non-null   str
 6   CustomerName  9994 non-null   str
 7   Segment       9994 non-null   str
 8   Country       9994 non-null   str
 9   City          9994 non-null   str
 10  State         9994 non-null   str
 11  PostalCode    9994 non-null   int64
 12  Region        9994 non-null   str
 13  ProductID     9994 non-null   str
 14  Category      9994 non-null   str
 15  SubCategory   9994 non-null   str
 16  ProductName   9994 non-null   str
 17  Sales         9994 non-null   float64
 18  Quantity      9994 non-null   int64
 19  Discount      9994 non-null   float64
 20  Profit        9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB
None

In [6]:
sales_df['OrderDate'] = pd.to_datetime(sales_df['OrderDate'], format='%m/%d/%Y')
print(sales_df.head(10))

   RowID         OrderID  OrderDate    ShipDate        ShipMode CustomerID  \
0      1  CA-2016-152156 2016-11-08  11/11/2016    Second Class   CG-12520
1      2  CA-2016-152156 2016-11-08  11/11/2016    Second Class   CG-12520
2      3  CA-2016-138688 2016-06-12   6/16/2016    Second Class   DV-13045
3      4  US-2015-108966 2015-10-11  10/18/2015  Standard Class   SO-20335
4      5  US-2015-108966 2015-10-11  10/18/2015  Standard Class   SO-20335
5      6  CA-2014-115812 2014-06-09   6/14/2014  Standard Class   BH-11710
6      7  CA-2014-115812 2014-06-09   6/14/2014  Standard Class   BH-11710
7      8  CA-2014-115812 2014-06-09   6/14/2014  Standard Class   BH-11710
8      9  CA-2014-115812 2014-06-09   6/14/2014  Standard Class   BH-11710
9     10  CA-2014-115812 2014-06-09   6/14/2014  Standard Class   BH-11710

      CustomerName    Segment        Country             City  ... PostalCode  \
0      Claire Gute   Consumer  United States        Henderson  ...      42420
1      Claire Gute   Consumer  United States        Henderson  ...      42420
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...      90036
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...      33311
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...      33311
5  Brosina Hoffman   Consumer  United States      Los Angeles  ...      90032
6  Brosina Hoffman   Consumer  United States      Los Angeles  ...      90032
7  Brosina Hoffman   Consumer  United States      Los Angeles  ...      90032
8  Brosina Hoffman   Consumer  United States      Los Angeles  ...      90032
9  Brosina Hoffman   Consumer  United States      Los Angeles  ...      90032

   Region        ProductID         Category  SubCategory  \
0   South  FUR-BO-10001798        Furniture    Bookcases
1   South  FUR-CH-10000454        Furniture       Chairs
2    West  OFF-LA-10000240  Office Supplies       Labels
3   South  FUR-TA-10000577        Furniture       Tables
4   South  OFF-ST-10000760  Office Supplies      Storage
5    West  FUR-FU-10001487        Furniture  Furnishings
6    West  OFF-AR-10002833  Office Supplies          Art
7    West  TEC-PH-10002275       Technology       Phones
8    West  OFF-BI-10003910  Office Supplies      Binders
9    West  OFF-AP-10002892  Office Supplies   Appliances

                                         ProductName     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                     Eldon Fold 'N Roll Cart System   22.3680         2
5  Eldon Expressions Wood and Plastic Desk Access...   48.8600         7
6                                         Newell 322    7.2800         4
7                     Mitel 5320 IP Phone VoIP phone  907.1520         6
8  DXL Angle-View Binders with Locking Rings by S...   18.5040         3
9                   Belkin F5C206VTEL 6 Outlet Surge  114.9000         5

   Discount    Profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164
5      0.00   14.1694
6      0.00    1.9656
7      0.20   90.7152
8      0.20    5.7825
9      0.00   34.4700

[10 rows x 21 columns]

In [7]:
sales_df['ShipDate'] = pd.to_datetime(sales_df['ShipDate'], format='%m/%d/%Y')
print(sales_df.head(10))

   RowID         OrderID  OrderDate   ShipDate        ShipMode CustomerID  \
0      1  CA-2016-152156 2016-11-08 2016-11-11    Second Class   CG-12520
1      2  CA-2016-152156 2016-11-08 2016-11-11    Second Class   CG-12520
2      3  CA-2016-138688 2016-06-12 2016-06-16    Second Class   DV-13045
3      4  US-2015-108966 2015-10-11 2015-10-18  Standard Class   SO-20335
4      5  US-2015-108966 2015-10-11 2015-10-18  Standard Class   SO-20335
5      6  CA-2014-115812 2014-06-09 2014-06-14  Standard Class   BH-11710
6      7  CA-2014-115812 2014-06-09 2014-06-14  Standard Class   BH-11710
7      8  CA-2014-115812 2014-06-09 2014-06-14  Standard Class   BH-11710
8      9  CA-2014-115812 2014-06-09 2014-06-14  Standard Class   BH-11710
9     10  CA-2014-115812 2014-06-09 2014-06-14  Standard Class   BH-11710

      CustomerName    Segment        Country             City  ... PostalCode  \
0      Claire Gute   Consumer  United States        Henderson  ...      42420
1      Claire Gute   Consumer  United States        Henderson  ...      42420
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...      90036
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...      33311
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...      33311
5  Brosina Hoffman   Consumer  United States      Los Angeles  ...      90032
6  Brosina Hoffman   Consumer  United States      Los Angeles  ...      90032
7  Brosina Hoffman   Consumer  United States      Los Angeles  ...      90032
8  Brosina Hoffman   Consumer  United States      Los Angeles  ...      90032
9  Brosina Hoffman   Consumer  United States      Los Angeles  ...      90032

   Region        ProductID         Category  SubCategory  \
0   South  FUR-BO-10001798        Furniture    Bookcases
1   South  FUR-CH-10000454        Furniture       Chairs
2    West  OFF-LA-10000240  Office Supplies       Labels
3   South  FUR-TA-10000577        Furniture       Tables
4   South  OFF-ST-10000760  Office Supplies      Storage
5    West  FUR-FU-10001487        Furniture  Furnishings
6    West  OFF-AR-10002833  Office Supplies          Art
7    West  TEC-PH-10002275       Technology       Phones
8    West  OFF-BI-10003910  Office Supplies      Binders
9    West  OFF-AP-10002892  Office Supplies   Appliances

                                         ProductName     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                     Eldon Fold 'N Roll Cart System   22.3680         2
5  Eldon Expressions Wood and Plastic Desk Access...   48.8600         7
6                                         Newell 322    7.2800         4
7                     Mitel 5320 IP Phone VoIP phone  907.1520         6
8  DXL Angle-View Binders with Locking Rings by S...   18.5040         3
9                   Belkin F5C206VTEL 6 Outlet Surge  114.9000         5

   Discount    Profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164
5      0.00   14.1694
6      0.00    1.9656
7      0.20   90.7152
8      0.20    5.7825
9      0.00   34.4700

[10 rows x 21 columns]

In [8]:
sales_df.head()

,RowID,OrderID,OrderDate,ShipDate,ShipMode,CustomerID,CustomerName,Segment,Country,City,...,PostalCode,Region,ProductID,Category,SubCategory,ProductName,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [9]:

sales_df['Sales'] = sales_df['Sales'].round(2)
sales_df['Profit'] = sales_df['Profit'].round(2)
print(sales_df.head())

   RowID         OrderID  OrderDate   ShipDate        ShipMode CustomerID  \
0      1  CA-2016-152156 2016-11-08 2016-11-11    Second Class   CG-12520
1      2  CA-2016-152156 2016-11-08 2016-11-11    Second Class   CG-12520
2      3  CA-2016-138688 2016-06-12 2016-06-16    Second Class   DV-13045
3      4  US-2015-108966 2015-10-11 2015-10-18  Standard Class   SO-20335
4      5  US-2015-108966 2015-10-11 2015-10-18  Standard Class   SO-20335

      CustomerName    Segment        Country             City  ... PostalCode  \
0      Claire Gute   Consumer  United States        Henderson  ...      42420
1      Claire Gute   Consumer  United States        Henderson  ...      42420
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...      90036
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...      33311
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...      33311

   Region        ProductID         Category SubCategory  \
0   South  FUR-BO-10001798        Furniture   Bookcases
1   South  FUR-CH-10000454        Furniture      Chairs
2    West  OFF-LA-10000240  Office Supplies      Labels
3   South  FUR-TA-10000577        Furniture      Tables
4   South  OFF-ST-10000760  Office Supplies     Storage

                                         ProductName   Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.96         2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.94         3
2  Self-Adhesive Address Labels for Typewriters b...   14.62         2
3      Bretford CR4500 Series Slim Rectangular Table  957.58         5
4                     Eldon Fold 'N Roll Cart System   22.37         2

   Discount  Profit
0      0.00   41.91
1      0.00  219.58
2      0.00    6.87
3      0.45 -383.03
4      0.20    2.52

[5 rows x 21 columns]

In [10]:
sales_df.describe(exclude=['str'])

,RowID,OrderDate,ShipDate,PostalCode,Sales,Quantity,Discount,Profit
count,9994.000000,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2016-04-30 00:07:12.259355,2016-05-03 23:06:58.571142,55190.379428,229.857980,3.789574,0.156203,28.656848
min,1.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,1040.000000,0.440000,1.000000,0.000000,-6599.980000
25%,2499.250000,2015-05-23 00:00:00,2015-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.730000
50%,4997.500000,2016-06-26 00:00:00,2016-06-29 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.665000
75%,7495.750000,2017-05-14 00:00:00,2017-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.360000
max,9994.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.980000
std,2885.163629,NaN,NaN,32063.693350,623.245104,2.225110,0.206452,234.260149

In [11]:
# check for date inconsistency
print("checking for date inconsistencies...")
inconsistency = sales_df[sales_df['OrderDate']>sales_df['ShipDate']][['OrderID','OrderDate','ShipDate']]

if inconsistency.isnull:
    print("All order dates are consistent (OrderDate < ShipDate)")
else:
    print("Date consistency is detected:")
    print(inconsistency)

checking for date inconsistencies...
All order dates are consistent (OrderDate < ShipDate)

### add latitude & longitude data

In [17]:
%pip install "kagglehub[pandas-datasets]"

Collecting kagglehub[pandas-datasets]
  Using cached kagglehub-0.4.3-py3-none-any.whl.metadata (40 kB)
Collecting kagglesdk<1.0,>=0.1.14 (from kagglehub[pandas-datasets])
  Downloading kagglesdk-0.1.15-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in /Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages (from kagglehub[pandas-datasets]) (26.0)
Collecting pyyaml (from kagglehub[pandas-datasets])
  Downloading pyyaml-6.0.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (2.4 kB)
Collecting requests (from kagglehub[pandas-datasets])
  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting tqdm (from kagglehub[pandas-datasets])
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: pandas in /Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages (from kagglehub[pandas-datasets]) (3.0.0)
Collecting protobuf (from kagglesdk<1.0,>=0.1.14->kagglehub[pandas-datasets])
  Downloading protobuf-6.33.5-cp39-abi3-macosx_10_9_universal2.whl.metadata (593 bytes)
Requirement already satisfied: numpy>=1.26.0 in /Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages (from pandas->kagglehub[pandas-datasets]) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages (from pandas->kagglehub[pandas-datasets]) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/aprilariestania/Downloads/sql_projects/.venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas->kagglehub[pandas-datasets]) (1.17.0)
Collecting charset_normalizer<4,>=2 (from requests->kagglehub[pandas-datasets])
  Downloading charset_normalizer-3.4.4-cp311-cp311-macosx_10_9_universal2.whl.metadata (37 kB)
Collecting idna<4,>=2.5 (from requests->kagglehub[pandas-datasets])
  Downloading idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.21.1 (from requests->kagglehub[pandas-datasets])
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2017.4.17 (from requests->kagglehub[pandas-datasets])
  Downloading certifi-2026.1.4-py3-none-any.whl.metadata (2.5 kB)
Downloading kagglehub-0.4.3-py3-none-any.whl (70 kB)
Downloading kagglesdk-0.1.15-py3-none-any.whl (160 kB)
Downloading protobuf-6.33.5-cp39-abi3-macosx_10_9_universal2.whl (427 kB)
Downloading pyyaml-6.0.3-cp311-cp311-macosx_11_0_arm64.whl (175 kB)
Downloading requests-2.32.5-py3-none-any.whl (64 kB)
Downloading charset_normalizer-3.4.4-cp311-cp311-macosx_10_9_universal2.whl (206 kB)
Downloading idna-3.11-py3-none-any.whl (71 kB)
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
Downloading certifi-2026.1.4-py3-none-any.whl (152 kB)
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
Installing collected packages: urllib3, tqdm, pyyaml, protobuf, idna, charset_normalizer, certifi, requests, kagglesdk, kagglehub
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/10 [kagglehub]10 [kagglehub]
Successfully installed certifi-2026.1.4 charset_normalizer-3.4.4 idna-3.11 kagglehub-0.4.3 kagglesdk-0.1.15 protobuf-6.33.5 pyyaml-6.0.3 requests-2.32.5 tqdm-4.67.3 urllib3-2.6.3

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [20]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "zip_lat_long.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "joeleichter/us-zip-codes-with-lat-and-long",
  file_path,
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

/var/folders/zp/xzv_vp9j36q8dwqr3db8h5900000gn/T/ipykernel_39805/3002451449.py:8: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Downloading to /Users/aprilariestania/.cache/kagglehub/datasets/joeleichter/us-zip-codes-with-lat-and-long/versions/1/zip_lat_long.csv...

100%|██████████| 906k/906k [00:01<00:00, 667kB/s]

First 5 records:    ZIP        LAT        LNG
0  601  18.180555 -66.749961
1  602  18.361945 -67.175597
2  603  18.455183 -67.119887
3  606  18.158345 -66.932911
4  610  18.295366 -67.125135

In [ ]:
# Make the column names consistent
df.columns = ['ZipCode', 'Latitude', 'Longitude']

In [27]:
# Merge sales data with zip code data
merged_df = pd.merge(sales_df, df, left_on='PostalCode', right_on='ZipCode', how='left')
print("Merged DataFrame head:", merged_df.head())

Merged DataFrame head:    RowID         OrderID  OrderDate   ShipDate        ShipMode CustomerID  \
0      1  CA-2016-152156 2016-11-08 2016-11-11    Second Class   CG-12520
1      2  CA-2016-152156 2016-11-08 2016-11-11    Second Class   CG-12520
2      3  CA-2016-138688 2016-06-12 2016-06-16    Second Class   DV-13045
3      4  US-2015-108966 2015-10-11 2015-10-18  Standard Class   SO-20335
4      5  US-2015-108966 2015-10-11 2015-10-18  Standard Class   SO-20335

      CustomerName    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...
1      Claire Gute   Consumer  United States        Henderson  ...
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...

          Category  SubCategory  \
0        Furniture    Bookcases
1        Furniture       Chairs
2  Office Supplies       Labels
3        Furniture       Tables
4  Office Supplies      Storage

                                         ProductName   Sales Quantity  \
0                  Bush Somerset Collection Bookcase  261.96        2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.94        3
2  Self-Adhesive Address Labels for Typewriters b...   14.62        2
3      Bretford CR4500 Series Slim Rectangular Table  957.58        5
4                     Eldon Fold 'N Roll Cart System   22.37        2

  Discount  Profit  ZipCode   Latitude   Longitude
0     0.00   41.91    42420  37.810608  -87.515004
1     0.00  219.58    42420  37.810608  -87.515004
2     0.00    6.87    90036  34.070410 -118.350411
3     0.45 -383.03    33311  26.144208  -80.172785
4     0.20    2.52    33311  26.144208  -80.172785

[5 rows x 24 columns]

In [29]:
merged_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 24 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   RowID         9994 non-null   int64
 1   OrderID       9994 non-null   str
 2   OrderDate     9994 non-null   datetime64[us]
 3   ShipDate      9994 non-null   datetime64[us]
 4   ShipMode      9994 non-null   str
 5   CustomerID    9994 non-null   str
 6   CustomerName  9994 non-null   str
 7   Segment       9994 non-null   str
 8   Country       9994 non-null   str
 9   City          9994 non-null   str
 10  State         9994 non-null   str
 11  PostalCode    9994 non-null   int64
 12  Region        9994 non-null   str
 13  ProductID     9994 non-null   str
 14  Category      9994 non-null   str
 15  SubCategory   9994 non-null   str
 16  ProductName   9994 non-null   str
 17  Sales         9994 non-null   float64
 18  Quantity      9994 non-null   int64
 19  Discount      9994 non-null   float64
 20  Profit        9994 non-null   float64
 21  ZipCode       9994 non-null   int64
 22  Latitude      9994 non-null   float64
 23  Longitude     9994 non-null   float64
dtypes: datetime64[us](2), float64(5), int64(4), str(13)
memory usage: 1.8 MB

### Load Data

In [32]:
merged_df.to_csv('../data/merged_sales_with_latlong.csv', index=False)

In [31]:
# close the connection
conn.close()